import 'classical_discovery_models.dart';

class ClassicalDiscoveryCatalog {
  ClassicalDiscoveryCatalog._();

  static final composers = <ClassicalComposer>[
    const ClassicalComposer(
      id: 'bach',
      nameKo: '바흐',
      nameOriginal: 'Johann Sebastian Bach',
      period: '바로크',
      aliases: ['J. S. Bach', '요한 제바스티안 바흐'],
    ),
    const ClassicalComposer(
      id: 'mozart',
      nameKo: '모차르트',
      nameOriginal: 'Wolfgang Amadeus Mozart',
      period: '고전',
      aliases: ['W. A. Mozart', '볼프강 아마데우스 모차르트'],
    ),
    const ClassicalComposer(
      id: 'beethoven',
      nameKo: '베토벤',
      nameOriginal: 'Ludwig van Beethoven',
      period: '고전',
      aliases: ['Beethoven', '루트비히 판 베토벤'],
    ),
    const ClassicalComposer(
      id: 'vivaldi',
      nameKo: '비발디',
      nameOriginal: 'Antonio Vivaldi',
      period: '바로크',
      aliases: ['안토니오 비발디'],
    ),
    const ClassicalComposer(
      id: 'chopin',
      nameKo: '쇼팽',
      nameOriginal: 'Frederic Chopin',
      period: '낭만',
      aliases: ['프레데리크 쇼팽', 'Chopin'],
    ),
    const ClassicalComposer(
      id: 'debussy',
      nameKo: '드뷔시',
      nameOriginal: 'Claude Debussy',
      period: '인상주의',
      aliases: ['클로드 드뷔시'],
    ),
    const ClassicalComposer(
      id: 'ravel',
      nameKo: '라벨',
      nameOriginal: 'Maurice Ravel',
      period: '근현대',
      aliases: ['모리스 라벨'],
    ),
    const ClassicalComposer(
      id: 'tchaikovsky',
      nameKo: '차이콥스키',
      nameOriginal: 'Pyotr Ilyich Tchaikovsky',
      period: '낭만',
      aliases: ['Tchaikovsky', '표트르 차이콥스키'],
    ),
    const ClassicalComposer(
      id: 'rachmaninoff',
      nameKo: '라흐마니노프',
      nameOriginal: 'Sergei Rachmaninoff',
      period: '근현대',
      aliases: ['Rachmaninoff', '라흐마니노프'],
    ),
    const ClassicalComposer(
      id: 'dvorak',
      nameKo: '드보르자크',
      nameOriginal: 'Antonin Dvorak',
      period: '낭만',
      aliases: ['Dvorak', '안토닌 드보르자크'],
    ),
    const ClassicalComposer(
      id: 'satie',
      nameKo: '사티',
      nameOriginal: 'Erik Satie',
      period: '근현대',
      aliases: ['에릭 사티'],
    ),
    const ClassicalComposer(
      id: 'saint-saens',
      nameKo: '생상스',
      nameOriginal: 'Camille Saint-Saens',
      period: '낭만',
      aliases: ['Saint-Saens', '카미유 생상스'],
    ),
    const ClassicalComposer(
      id: 'elgar',
      nameKo: '엘가',
      nameOriginal: 'Edward Elgar',
      period: '낭만',
      aliases: ['Elgar', '에드워드 엘가'],
    ),
    const ClassicalComposer(
      id: 'handel',
      nameKo: '헨델',
      nameOriginal: 'George Frideric Handel',
      period: '바로크',
      aliases: ['Handel', '게오르크 프리드리히 헨델'],
    ),
    const ClassicalComposer(
      id: 'mendelssohn',
      nameKo: '멘델스존',
      nameOriginal: 'Felix Mendelssohn',
      period: '낭만',
      aliases: ['Mendelssohn', '펠릭스 멘델스존'],
    ),
    const ClassicalComposer(
      id: 'pachelbel',
      nameKo: '파헬벨',
      nameOriginal: 'Johann Pachelbel',
      period: '바로크',
      aliases: ['Pachelbel', '요한 파헬벨'],
    ),
    const ClassicalComposer(
      id: 'liszt',
      nameKo: '리스트',
      nameOriginal: 'Franz Liszt',
      period: '낭만',
      aliases: ['Liszt', '프란츠 리스트'],
    ),
    const ClassicalComposer(
      id: 'schubert',
      nameKo: '슈베르트',
      nameOriginal: 'Franz Schubert',
      period: '낭만',
      aliases: ['Schubert', '프란츠 슈베르트'],
    ),
    const ClassicalComposer(
      id: 'brahms',
      nameKo: '브람스',
      nameOriginal: 'Johannes Brahms',
      period: '낭만',
      aliases: ['Brahms', '요하네스 브람스'],
    ),
    const ClassicalComposer(
      id: 'grieg',
      nameKo: '그리그',
      nameOriginal: 'Edvard Grieg',
      period: '낭만',
      aliases: ['Grieg', '에드바르 그리그'],
    ),
    const ClassicalComposer(
      id: 'mussorgsky',
      nameKo: '무소륵스키',
      nameOriginal: 'Modest Mussorgsky',
      period: '낭만',
      aliases: ['Mussorgsky', '모데스트 무소륵스키'],
    ),
    const ClassicalComposer(
      id: 'rimsky-korsakov',
      nameKo: '림스키코르사코프',
      nameOriginal: 'Nikolai Rimsky-Korsakov',
      period: '낭만',
      aliases: ['Rimsky-Korsakov', '림스키 코르사코프'],
    ),
    const ClassicalComposer(
      id: 'mahler',
      nameKo: '말러',
      nameOriginal: 'Gustav Mahler',
      period: '근현대',
      aliases: ['Mahler', '구스타프 말러'],
    ),
    const ClassicalComposer(
      id: 'sibelius',
      nameKo: '시벨리우스',
      nameOriginal: 'Jean Sibelius',
      period: '근현대',
      aliases: ['Sibelius', '장 시벨리우스'],
    ),
    const ClassicalComposer(
      id: 'haydn',
      nameKo: '하이든',
      nameOriginal: 'Joseph Haydn',
      period: '고전',
      aliases: ['Haydn', '요제프 하이든'],
    ),
    const ClassicalComposer(
      id: 'scarlatti',
      nameKo: '스카를라티',
      nameOriginal: 'Domenico Scarlatti',
      period: '바로크',
      aliases: ['Scarlatti', '도메니코 스카를라티'],
    ),
    const ClassicalComposer(
      id: 'purcell',
      nameKo: '퍼셀',
      nameOriginal: 'Henry Purcell',
      period: '바로크',
      aliases: ['Purcell', '헨리 퍼셀'],
    ),
    const ClassicalComposer(
      id: 'faure',
      nameKo: '포레',
      nameOriginal: 'Gabriel Faure',
      period: '근현대',
      aliases: ['Faure', '가브리엘 포레'],
    ),
    const ClassicalComposer(
      id: 'bizet',
      nameKo: '비제',
      nameOriginal: 'Georges Bizet',
      period: '낭만',
      aliases: ['Bizet', '조르주 비제'],
    ),
    const ClassicalComposer(
      id: 'puccini',
      nameKo: '푸치니',
      nameOriginal: 'Giacomo Puccini',
      period: '근현대',
      aliases: ['Puccini', '자코모 푸치니'],
    ),
    const ClassicalComposer(
      id: 'verdi',
      nameKo: '베르디',
      nameOriginal: 'Giuseppe Verdi',
      period: '낭만',
      aliases: ['Verdi', '주세페 베르디'],
    ),
    const ClassicalComposer(
      id: 'rossini',
      nameKo: '로시니',
      nameOriginal: 'Gioachino Rossini',
      period: '낭만',
      aliases: ['Rossini', '조아키노 로시니'],
    ),
    const ClassicalComposer(
      id: 'strauss-ii',
      nameKo: '요한 슈트라우스 2세',
      nameOriginal: 'Johann Strauss II',
      period: '낭만',
      aliases: ['Strauss II', '요한 슈트라우스'],
    ),
    const ClassicalComposer(
      id: 'holst',
      nameKo: '홀스트',
      nameOriginal: 'Gustav Holst',
      period: '근현대',
      aliases: ['Holst', '구스타브 홀스트'],
    ),
  ];

  static final works = <ClassicalWork>[
    _work(
      id: 'bach-cello-suite-1-prelude',
      titleKo: '무반주 첼로 모음곡 1번 프렐류드',
      titleOriginal: 'Cello Suite No. 1 in G major, Prelude',
      composerId: 'bach',
      composerKo: '바흐',
      composerOriginal: 'Johann Sebastian Bach',
      period: '바로크',
      instrumentation: '첼로',
      durationSeconds: 150,
      catalogNumber: 'BWV 1007',
      aliases: ['첼로 모음곡', '바흐 첼로 프렐류드'],
      moodTags: ['차분한', '맑은', '반복'],
      contextTags: ['처음 듣기', '아침', '독주'],
      prompt: '낮은 음에서 높은 음으로 물결처럼 올라가는 패턴만 따라가 보세요.',
      relatedWorkIds: ['saint-saens-swan', 'bach-air'],
      concertIds: ['concert-baroque-night'],
    ),
    _work(
      id: 'bach-air',
      titleKo: 'G선상의 아리아',
      titleOriginal: 'Orchestral Suite No. 3, Air',
      composerId: 'bach',
      composerKo: '바흐',
      composerOriginal: 'Johann Sebastian Bach',
      period: '바로크',
      instrumentation: '현악합주',
      durationSeconds: 300,
      catalogNumber: 'BWV 1068',
      aliases: ['Air on the G String', '지선상의 아리아'],
      moodTags: ['차분한', '따뜻한', '선율'],
      contextTags: ['밤', '처음 듣기', '공연 전'],
      prompt: '선율이 거의 걷는 속도로 움직이는지 들어보세요.',
      relatedWorkIds: ['bach-cello-suite-1-prelude', 'elgar-nimrod'],
      concertIds: ['concert-baroque-night'],
    ),
    _work(
      id: 'mozart-eine-kleine',
      titleKo: '아이네 클라이네 나흐트무지크',
      titleOriginal: 'Eine kleine Nachtmusik',
      composerId: 'mozart',
      composerKo: '모차르트',
      composerOriginal: 'Wolfgang Amadeus Mozart',
      period: '고전',
      instrumentation: '현악합주',
      durationSeconds: 1200,
      catalogNumber: 'K. 525',
      aliases: ['작은 밤의 음악', '세레나데 13번'],
      moodTags: ['밝은', '경쾌한', '익숙한'],
      contextTags: ['처음 듣기', '산책', '공연 전'],
      prompt: '첫 네 음이 대답처럼 반복되는 구조를 붙잡아 보세요.',
      relatedWorkIds: ['mozart-piano-sonata-k545', 'vivaldi-spring'],
      concertIds: ['concert-classic-starter'],
    ),
    _work(
      id: 'mozart-piano-sonata-k545',
      titleKo: '피아노 소나타 16번',
      titleOriginal: 'Piano Sonata No. 16 in C major',
      composerId: 'mozart',
      composerKo: '모차르트',
      composerOriginal: 'Wolfgang Amadeus Mozart',
      period: '고전',
      instrumentation: '피아노',
      durationSeconds: 840,
      catalogNumber: 'K. 545',
      aliases: ['쉬운 소나타', '소나타 K545'],
      moodTags: ['밝은', '단정한', '명료한'],
      contextTags: ['처음 듣기', '피아노', '연습'],
      prompt: '오른손 멜로디와 왼손 반주가 얼마나 또렷하게 나뉘는지 들어보세요.',
      relatedWorkIds: ['beethoven-moonlight', 'chopin-nocturne-op9-2'],
      concertIds: ['concert-piano-evening'],
    ),
    _work(
      id: 'beethoven-symphony-5',
      titleKo: '교향곡 5번 운명',
      titleOriginal: 'Symphony No. 5 in C minor',
      composerId: 'beethoven',
      composerKo: '베토벤',
      composerOriginal: 'Ludwig van Beethoven',
      period: '고전',
      instrumentation: '오케스트라',
      durationSeconds: 1980,
      catalogNumber: 'Op. 67',
      aliases: ['운명 교향곡', '따따따딴'],
      moodTags: ['강렬한', '긴장', '웅장한'],
      contextTags: ['처음 듣기', '공연 전', '오케스트라'],
      prompt: '짧은 리듬 하나가 계속 모습을 바꾸며 돌아오는지만 들어도 충분합니다.',
      relatedWorkIds: ['beethoven-symphony-9', 'dvorak-new-world'],
      concertIds: ['concert-symphony-starter'],
    ),
    _work(
      id: 'beethoven-symphony-9',
      titleKo: '교향곡 9번 합창',
      titleOriginal: 'Symphony No. 9 in D minor',
      composerId: 'beethoven',
      composerKo: '베토벤',
      composerOriginal: 'Ludwig van Beethoven',
      period: '고전',
      instrumentation: '오케스트라',
      durationSeconds: 4200,
      catalogNumber: 'Op. 125',
      aliases: ['합창 교향곡', '환희의 송가', 'Ode to Joy'],
      moodTags: ['웅장한', '희망적인', '합창'],
      contextTags: ['공연 전', '오케스트라', '성악'],
      prompt: '익숙한 선율이 아주 단순하게 시작해 점점 커지는 순간을 기다려 보세요.',
      relatedWorkIds: ['beethoven-symphony-5', 'handel-hallelujah'],
      concertIds: ['concert-symphony-starter'],
    ),
    _work(
      id: 'beethoven-moonlight',
      titleKo: '월광 소나타 1악장',
      titleOriginal: 'Piano Sonata No. 14, I. Adagio sostenuto',
      composerId: 'beethoven',
      composerKo: '베토벤',
      composerOriginal: 'Ludwig van Beethoven',
      period: '고전',
      instrumentation: '피아노',
      durationSeconds: 360,
      catalogNumber: 'Op. 27 No. 2',
      aliases: ['월광', 'Moonlight Sonata'],
      moodTags: ['어두운', '차분한', '반복'],
      contextTags: ['밤', '피아노', '처음 듣기'],
      prompt: '멜로디보다 왼손의 같은 물결이 계속 흐르는 느낌을 먼저 들어보세요.',
      relatedWorkIds: ['chopin-nocturne-op9-2', 'debussy-clair-de-lune'],
      concertIds: ['concert-piano-evening'],
    ),
    _work(
      id: 'beethoven-fur-elise',
      titleKo: '엘리제를 위하여',
      titleOriginal: 'Fur Elise',
      composerId: 'beethoven',
      composerKo: '베토벤',
      composerOriginal: 'Ludwig van Beethoven',
      period: '고전',
      instrumentation: '피아노',
      durationSeconds: 180,
      catalogNumber: 'WoO 59',
      aliases: ['엘리제', 'Fur Elise'],
      moodTags: ['익숙한', '가벼운', '선율'],
      contextTags: ['처음 듣기', '피아노', '연습'],
      prompt: '처음 다섯 음이 질문처럼 돌아오는 느낌을 잡아보세요.',
      relatedWorkIds: ['mozart-piano-sonata-k545', 'satie-gymnopedie-1'],
      concertIds: ['concert-piano-evening'],
    ),
    _work(
      id: 'vivaldi-spring',
      titleKo: '사계 중 봄 1악장',
      titleOriginal: 'The Four Seasons: Spring, I. Allegro',
      composerId: 'vivaldi',
      composerKo: '비발디',
      composerOriginal: 'Antonio Vivaldi',
      period: '바로크',
      instrumentation: '바이올린',
      durationSeconds: 210,
      catalogNumber: 'RV 269',
      aliases: ['사계 봄', 'Four Seasons Spring'],
      moodTags: ['밝은', '경쾌한', '익숙한'],
      contextTags: ['아침', '처음 듣기', '바이올린'],
      prompt: '새소리처럼 짧게 튀는 바이올린 소리를 찾아보세요.',
      relatedWorkIds: ['mozart-eine-kleine', 'tchaikovsky-nutcracker-waltz'],
      concertIds: ['concert-classic-starter'],
    ),
    _work(
      id: 'chopin-nocturne-op9-2',
      titleKo: '녹턴 2번',
      titleOriginal: 'Nocturne in E-flat major',
      composerId: 'chopin',
      composerKo: '쇼팽',
      composerOriginal: 'Frederic Chopin',
      period: '낭만',
      instrumentation: '피아노',
      durationSeconds: 270,
      catalogNumber: 'Op. 9 No. 2',
      aliases: ['쇼팽 녹턴', 'Nocturne Op.9 No.2'],
      moodTags: ['로맨틱한', '밤', '선율'],
      contextTags: ['밤', '피아노', '처음 듣기'],
      prompt: '멜로디가 말하듯 조금씩 늦춰지고 당겨지는 느낌을 들어보세요.',
      relatedWorkIds: ['debussy-clair-de-lune', 'beethoven-moonlight'],
      concertIds: ['concert-piano-evening'],
    ),
    _work(
      id: 'chopin-revolutionary',
      titleKo: '혁명 에튀드',
      titleOriginal: 'Etude in C minor',
      composerId: 'chopin',
      composerKo: '쇼팽',
      composerOriginal: 'Frederic Chopin',
      period: '낭만',
      instrumentation: '피아노',
      durationSeconds: 150,
      catalogNumber: 'Op. 10 No. 12',
      aliases: ['혁명', 'Revolutionary Etude'],
      moodTags: ['격정적인', '빠른', '강렬한'],
      contextTags: ['피아노', '연습', '집중'],
      prompt: '왼손이 멈추지 않고 몰아치는 에너지만 따라가 보세요.',
      relatedWorkIds: ['rachmaninoff-piano-concerto-2', 'beethoven-symphony-5'],
      concertIds: ['concert-piano-evening'],
    ),
    _work(
      id: 'debussy-clair-de-lune',
      titleKo: '달빛',
      titleOriginal: 'Clair de lune',
      composerId: 'debussy',
      composerKo: '드뷔시',
      composerOriginal: 'Claude Debussy',
      period: '인상주의',
      instrumentation: '피아노',
      durationSeconds: 300,
      catalogNumber: 'L. 75',
      aliases: ['클레르 드 룬', '드뷔시 달빛'],
      moodTags: ['몽환적인', '밤', '부드러운'],
      contextTags: ['밤', '피아노', '처음 듣기'],
      prompt: '선율보다 피아노 소리가 번지는 색감만 먼저 들어보세요.',
      relatedWorkIds: ['satie-gymnopedie-1', 'ravel-bolero'],
      concertIds: ['concert-impression-night'],
    ),
    _work(
      id: 'ravel-bolero',
      titleKo: '볼레로',
      titleOriginal: 'Bolero',
      composerId: 'ravel',
      composerKo: '라벨',
      composerOriginal: 'Maurice Ravel',
      period: '근현대',
      instrumentation: '오케스트라',
      durationSeconds: 900,
      catalogNumber: 'M. 81',
      aliases: ['Bolero'],
      moodTags: ['반복', '점점 커지는', '관능적인'],
      contextTags: ['오케스트라', '집중', '공연 전'],
      prompt: '같은 리듬이 악기만 바뀌며 계속 커지는 것을 들어보세요.',
      relatedWorkIds: ['debussy-clair-de-lune', 'beethoven-symphony-5'],
      concertIds: ['concert-impression-night'],
    ),
    _work(
      id: 'tchaikovsky-nutcracker-waltz',
      titleKo: '꽃의 왈츠',
      titleOriginal: 'The Nutcracker: Waltz of the Flowers',
      composerId: 'tchaikovsky',
      composerKo: '차이콥스키',
      composerOriginal: 'Pyotr Ilyich Tchaikovsky',
      period: '낭만',
      instrumentation: '오케스트라',
      durationSeconds: 420,
      catalogNumber: 'Op. 71',
      aliases: ['호두까기 인형', 'Waltz of the Flowers'],
      moodTags: ['화려한', '밝은', '왈츠'],
      contextTags: ['오케스트라', '공연 전', '겨울'],
      prompt: '하프가 문을 열고 왈츠가 넓어지는 순간을 기다려 보세요.',
      relatedWorkIds: ['tchaikovsky-swan-lake', 'vivaldi-spring'],
      concertIds: ['concert-classic-starter'],
    ),
    _work(
      id: 'tchaikovsky-swan-lake',
      titleKo: '백조의 호수 정경',
      titleOriginal: 'Swan Lake: Scene',
      composerId: 'tchaikovsky',
      composerKo: '차이콥스키',
      composerOriginal: 'Pyotr Ilyich Tchaikovsky',
      period: '낭만',
      instrumentation: '오케스트라',
      durationSeconds: 180,
      catalogNumber: 'Op. 20',
      aliases: ['백조의 호수', 'Swan Lake'],
      moodTags: ['극적인', '어두운', '선율'],
      contextTags: ['오케스트라', '발레', '공연 전'],
      prompt: '오보에 선율이 긴장과 슬픔을 한 번에 만드는지 들어보세요.',
      relatedWorkIds: ['tchaikovsky-nutcracker-waltz', 'saint-saens-swan'],
      concertIds: ['concert-symphony-starter'],
    ),
    _work(
      id: 'rachmaninoff-piano-concerto-2',
      titleKo: '피아노 협주곡 2번 2악장',
      titleOriginal: 'Piano Concerto No. 2, II. Adagio sostenuto',
      composerId: 'rachmaninoff',
      composerKo: '라흐마니노프',
      composerOriginal: 'Sergei Rachmaninoff',
      period: '근현대',
      instrumentation: '피아노',
      durationSeconds: 660,
      catalogNumber: 'Op. 18',
      aliases: ['라흐 2번', '라흐마니노프 피협 2번'],
      moodTags: ['로맨틱한', '풍성한', '밤'],
      contextTags: ['피아노', '공연 전', '집중'],
      prompt: '피아노가 반주처럼 시작한 뒤 선율을 넘겨받는 순간을 들어보세요.',
      relatedWorkIds: ['chopin-nocturne-op9-2', 'dvorak-new-world'],
      concertIds: ['concert-piano-evening'],
    ),
    _work(
      id: 'dvorak-new-world',
      titleKo: '신세계 교향곡 2악장',
      titleOriginal: 'Symphony No. 9 From the New World, II. Largo',
      composerId: 'dvorak',
      composerKo: '드보르자크',
      composerOriginal: 'Antonin Dvorak',
      period: '낭만',
      instrumentation: '오케스트라',
      durationSeconds: 720,
      catalogNumber: 'Op. 95',
      aliases: ['신세계', 'From the New World'],
      moodTags: ['따뜻한', '그리운', '선율'],
      contextTags: ['오케스트라', '밤', '공연 전'],
      prompt: '잉글리시 호른 선율이 아주 멀리서 오는 노래처럼 들리는지 느껴보세요.',
      relatedWorkIds: ['elgar-nimrod', 'beethoven-symphony-9'],
      concertIds: ['concert-symphony-starter'],
    ),
    _work(
      id: 'elgar-nimrod',
      titleKo: '님로드',
      titleOriginal: 'Enigma Variations: Nimrod',
      composerId: 'elgar',
      composerKo: '엘가',
      composerOriginal: 'Edward Elgar',
      period: '낭만',
      instrumentation: '오케스트라',
      durationSeconds: 240,
      catalogNumber: 'Op. 36',
      aliases: ['Nimrod', '수수께끼 변주곡'],
      moodTags: ['따뜻한', '장엄한', '위로'],
      contextTags: ['오케스트라', '밤', '처음 듣기'],
      prompt: '아주 작게 시작한 화음이 천천히 커지는 호흡을 따라가 보세요.',
      relatedWorkIds: ['bach-air', 'dvorak-new-world'],
      concertIds: ['concert-symphony-starter'],
    ),
    _work(
      id: 'satie-gymnopedie-1',
      titleKo: '짐노페디 1번',
      titleOriginal: 'Gymnopedie No. 1',
      composerId: 'satie',
      composerKo: '사티',
      composerOriginal: 'Erik Satie',
      period: '근현대',
      instrumentation: '피아노',
      durationSeconds: 210,
      catalogNumber: '',
      aliases: ['Gymnopedie', '사티 짐노페디'],
      moodTags: ['차분한', '몽환적인', '느린'],
      contextTags: ['밤', '피아노', '집중'],
      prompt: '왼손의 느린 발걸음 위에 멜로디가 떠 있는 느낌만 들어보세요.',
      relatedWorkIds: ['debussy-clair-de-lune', 'beethoven-moonlight'],
      concertIds: ['concert-impression-night'],
    ),
    _work(
      id: 'saint-saens-swan',
      titleKo: '백조',
      titleOriginal: 'The Carnival of the Animals: The Swan',
      composerId: 'saint-saens',
      composerKo: '생상스',
      composerOriginal: 'Camille Saint-Saens',
      period: '낭만',
      instrumentation: '첼로',
      durationSeconds: 180,
      catalogNumber: '',
      aliases: ['동물의 사육제 백조', 'The Swan'],
      moodTags: ['우아한', '차분한', '선율'],
      contextTags: ['첼로', '처음 듣기', '밤'],
      prompt: '첼로 선율 아래 피아노가 물결처럼 움직이는지 들어보세요.',
      relatedWorkIds: ['bach-cello-suite-1-prelude', 'tchaikovsky-swan-lake'],
      concertIds: ['concert-baroque-night'],
    ),
    _work(
      id: 'handel-hallelujah',
      titleKo: '할렐루야',
      titleOriginal: 'Messiah: Hallelujah Chorus',
      composerId: 'handel',
      composerKo: '헨델',
      composerOriginal: 'George Frideric Handel',
      period: '바로크',
      instrumentation: '합창',
      durationSeconds: 240,
      catalogNumber: 'HWV 56',
      aliases: ['메시아 할렐루야', 'Hallelujah Chorus'],
      moodTags: ['웅장한', '밝은', '합창'],
      contextTags: ['성악', '공연 전', '처음 듣기'],
      prompt: '합창이 짧은 말 조각을 서로 주고받으며 커지는 느낌을 들어보세요.',
      relatedWorkIds: ['beethoven-symphony-9', 'bach-air'],
      concertIds: ['concert-chorus-night'],
    ),
    _work(
      id: 'mendelssohn-wedding-march',
      titleKo: '축혼 행진곡',
      titleOriginal: 'Wedding March',
      composerId: 'mendelssohn',
      composerKo: '멘델스존',
      composerOriginal: 'Felix Mendelssohn',
      period: '낭만',
      instrumentation: '오케스트라',
      durationSeconds: 300,
      catalogNumber: 'Op. 61',
      aliases: ['결혼행진곡', 'Wedding March'],
      moodTags: ['밝은', '화려한', '익숙한'],
      contextTags: ['처음 듣기', '오케스트라', '행사'],
      prompt: '누구나 아는 첫 화음 뒤에 관악기가 얼마나 환하게 터지는지 들어보세요.',
      relatedWorkIds: ['vivaldi-spring', 'mozart-eine-kleine'],
      concertIds: ['concert-classic-starter'],
    ),
    _work(
      id: 'pachelbel-canon',
      titleKo: '캐논',
      titleOriginal: 'Canon in D',
      composerId: 'pachelbel',
      composerKo: '파헬벨',
      composerOriginal: 'Johann Pachelbel',
      period: '바로크',
      instrumentation: '현악합주',
      durationSeconds: 330,
      catalogNumber: '',
      aliases: ['파헬벨 캐논', 'Canon'],
      moodTags: ['익숙한', '반복', '따뜻한'],
      contextTags: ['처음 듣기', '현악합주', '행사'],
      prompt: '같은 베이스가 반복되는 동안 위의 선율만 조금씩 쌓이는지 들어보세요.',
      relatedWorkIds: ['bach-air', 'vivaldi-spring'],
      concertIds: ['concert-classic-starter'],
    ),
    _work(
      id: 'liszt-liebestraum-3',
      titleKo: '사랑의 꿈 3번',
      titleOriginal: 'Liebestraum No. 3',
      composerId: 'liszt',
      composerKo: '리스트',
      composerOriginal: 'Franz Liszt',
      period: '낭만',
      instrumentation: '피아노',
      durationSeconds: 300,
      catalogNumber: 'S. 541',
      aliases: ['리스트 사랑의 꿈', 'Liebestraum'],
      moodTags: ['로맨틱한', '화려한', '선율'],
      contextTags: ['피아노', '밤', '공연 전'],
      prompt: '멜로디가 점점 넓게 펼쳐지는 순간까지 서두르지 않고 기다려 보세요.',
      relatedWorkIds: [
        'chopin-nocturne-op9-2',
        'rachmaninoff-piano-concerto-2',
      ],
      concertIds: ['concert-piano-evening'],
    ),
    _work(
      id: 'schubert-ave-maria',
      titleKo: '아베 마리아',
      titleOriginal: 'Ave Maria',
      composerId: 'schubert',
      composerKo: '슈베르트',
      composerOriginal: 'Franz Schubert',
      period: '낭만',
      instrumentation: '성악',
      durationSeconds: 300,
      catalogNumber: 'D. 839',
      aliases: ['슈베르트 아베마리아', 'Ellens dritter Gesang'],
      moodTags: ['차분한', '기도', '선율'],
      contextTags: ['성악', '밤', '처음 듣기'],
      prompt: '목소리가 긴 호흡으로 한 문장을 끝까지 가져가는지 들어보세요.',
      relatedWorkIds: ['handel-hallelujah', 'saint-saens-swan'],
      concertIds: ['concert-chorus-night'],
    ),
    _work(
      id: 'brahms-lullaby',
      titleKo: '자장가',
      titleOriginal: 'Wiegenlied',
      composerId: 'brahms',
      composerKo: '브람스',
      composerOriginal: 'Johannes Brahms',
      period: '낭만',
      instrumentation: '성악',
      durationSeconds: 180,
      catalogNumber: 'Op. 49 No. 4',
      aliases: ['브람스 자장가', 'Wiegenlied'],
      moodTags: ['차분한', '따뜻한', '선율'],
      contextTags: ['밤', '성악', '처음 듣기'],
      prompt: '반복되는 흔들림 위에서 선율이 얼마나 작게 숨 쉬는지 들어보세요.',
      relatedWorkIds: ['schubert-ave-maria', 'faure-pavane'],
      concertIds: const [],
    ),
    _work(
      id: 'brahms-hungarian-dance-5',
      titleKo: '헝가리 무곡 5번',
      titleOriginal: 'Hungarian Dance No. 5',
      composerId: 'brahms',
      composerKo: '브람스',
      composerOriginal: 'Johannes Brahms',
      period: '낭만',
      instrumentation: '오케스트라',
      durationSeconds: 180,
      catalogNumber: 'WoO 1 No. 5',
      aliases: ['브람스 헝가리 무곡 5번', 'Hungarian Dance 5'],
      moodTags: ['밝은', '빠른', '익숙한'],
      contextTags: ['산책', '오케스트라', '처음 듣기'],
      prompt: '느린 듯 시작했다가 갑자기 속도가 바뀌는 장난을 따라가 보세요.',
      relatedWorkIds: ['rossini-william-tell', 'bizet-carmen-habanera'],
      concertIds: const [],
    ),
    _work(
      id: 'brahms-symphony-3-iii',
      titleKo: '교향곡 3번 3악장',
      titleOriginal: 'Symphony No. 3: III. Poco allegretto',
      composerId: 'brahms',
      composerKo: '브람스',
      composerOriginal: 'Johannes Brahms',
      period: '낭만',
      instrumentation: '오케스트라',
      durationSeconds: 360,
      catalogNumber: 'Op. 90',
      aliases: ['브람스 3번 3악장', 'Poco allegretto'],
      moodTags: ['따뜻한', '그리운', '선율'],
      contextTags: ['밤', '오케스트라', '공연 전'],
      prompt: '첫 선율이 돌아올 때마다 색이 조금씩 어두워지는지 들어보세요.',
      relatedWorkIds: ['dvorak-new-world', 'elgar-nimrod'],
      concertIds: const [],
    ),
    _work(
      id: 'grieg-morning-mood',
      titleKo: '아침 기분',
      titleOriginal: 'Peer Gynt: Morning Mood',
      composerId: 'grieg',
      composerKo: '그리그',
      composerOriginal: 'Edvard Grieg',
      period: '낭만',
      instrumentation: '오케스트라',
      durationSeconds: 240,
      catalogNumber: 'Op. 46 No. 1',
      aliases: ['그리그 아침', 'Morning Mood'],
      moodTags: ['맑은', '밝은', '익숙한'],
      contextTags: ['아침', '처음 듣기', '오케스트라'],
      prompt: '목관의 짧은 선율이 현악기로 옮겨갈 때 공기가 넓어지는지 들어보세요.',
      relatedWorkIds: ['vivaldi-spring', 'mozart-eine-kleine'],
      concertIds: const [],
    ),
    _work(
      id: 'grieg-in-the-hall',
      titleKo: '산왕의 궁전에서',
      titleOriginal: 'Peer Gynt: In the Hall of the Mountain King',
      composerId: 'grieg',
      composerKo: '그리그',
      composerOriginal: 'Edvard Grieg',
      period: '낭만',
      instrumentation: '오케스트라',
      durationSeconds: 160,
      catalogNumber: 'Op. 46 No. 4',
      aliases: ['산속 마왕의 궁전에서', 'In the Hall of the Mountain King'],
      moodTags: ['긴장', '점점 커지는', '익숙한'],
      contextTags: ['집중', '오케스트라', '처음 듣기'],
      prompt: '같은 선율이 반복될수록 속도와 음량이 어떻게 몰려오는지 들어보세요.',
      relatedWorkIds: ['ravel-bolero', 'beethoven-symphony-5'],
      concertIds: const [],
    ),
    _work(
      id: 'mussorgsky-great-gate',
      titleKo: '키이우의 대문',
      titleOriginal: 'Pictures at an Exhibition: The Great Gate of Kiev',
      composerId: 'mussorgsky',
      composerKo: '무소륵스키',
      composerOriginal: 'Modest Mussorgsky',
      period: '낭만',
      instrumentation: '오케스트라',
      durationSeconds: 360,
      catalogNumber: '',
      aliases: ['전람회의 그림 대문', 'Great Gate of Kiev'],
      moodTags: ['웅장한', '장엄한', '화려한'],
      contextTags: ['오케스트라', '공연 전', '처음 듣기'],
      prompt: '종소리 같은 화음 사이로 행진 선율이 얼마나 크게 열리는지 들어보세요.',
      relatedWorkIds: ['holst-jupiter', 'beethoven-symphony-9'],
      concertIds: const [],
    ),
    _work(
      id: 'rimsky-flight-bumblebee',
      titleKo: '왕벌의 비행',
      titleOriginal: 'Flight of the Bumblebee',
      composerId: 'rimsky-korsakov',
      composerKo: '림스키코르사코프',
      composerOriginal: 'Nikolai Rimsky-Korsakov',
      period: '낭만',
      instrumentation: '오케스트라',
      durationSeconds: 90,
      catalogNumber: '',
      aliases: ['왕벌의 비행', 'Bumblebee'],
      moodTags: ['빠른', '화려한', '긴장'],
      contextTags: ['집중', '오케스트라', '처음 듣기'],
      prompt: '거의 쉬지 않는 음표들이 악기 사이를 얼마나 빠르게 지나가는지 들어보세요.',
      relatedWorkIds: ['chopin-revolutionary', 'rossini-william-tell'],
      concertIds: const [],
    ),
    _work(
      id: 'mahler-adagietto',
      titleKo: '교향곡 5번 아다지에토',
      titleOriginal: 'Symphony No. 5: IV. Adagietto',
      composerId: 'mahler',
      composerKo: '말러',
      composerOriginal: 'Gustav Mahler',
      period: '근현대',
      instrumentation: '오케스트라',
      durationSeconds: 600,
      catalogNumber: 'Symphony No. 5',
      aliases: ['말러 아다지에토', 'Adagietto'],
      moodTags: ['차분한', '애틋한', '선율'],
      contextTags: ['밤', '오케스트라', '공연 전'],
      prompt: '현악기의 긴 숨 위에 하프가 조용히 시간을 세는 순간을 들어보세요.',
      relatedWorkIds: ['elgar-nimrod', 'faure-pavane'],
      concertIds: const [],
    ),
    _work(
      id: 'sibelius-finlandia',
      titleKo: '핀란디아',
      titleOriginal: 'Finlandia',
      composerId: 'sibelius',
      composerKo: '시벨리우스',
      composerOriginal: 'Jean Sibelius',
      period: '근현대',
      instrumentation: '오케스트라',
      durationSeconds: 480,
      catalogNumber: 'Op. 26',
      aliases: ['시벨리우스 핀란디아', 'Finlandia'],
      moodTags: ['웅장한', '희망적인', '장엄한'],
      contextTags: ['오케스트라', '공연 전', '집중'],
      prompt: '어두운 금관 화음 뒤에 찬가처럼 열리는 선율을 기다려 보세요.',
      relatedWorkIds: ['beethoven-symphony-9', 'holst-jupiter'],
      concertIds: const [],
    ),
    _work(
      id: 'haydn-surprise-symphony',
      titleKo: '놀람 교향곡 2악장',
      titleOriginal: 'Symphony No. 94: II. Andante',
      composerId: 'haydn',
      composerKo: '하이든',
      composerOriginal: 'Joseph Haydn',
      period: '고전',
      instrumentation: '오케스트라',
      durationSeconds: 360,
      catalogNumber: 'Hob. I:94',
      aliases: ['하이든 놀람', 'Surprise Symphony'],
      moodTags: ['익숙한', '단정한', '유머'],
      contextTags: ['처음 듣기', '오케스트라', '공연 전'],
      prompt: '아주 조용한 반복 뒤에 갑자기 튀어나오는 한 방을 기다려 보세요.',
      relatedWorkIds: ['mozart-eine-kleine', 'beethoven-fur-elise'],
      concertIds: const [],
    ),
    _work(
      id: 'haydn-cello-concerto-c',
      titleKo: '첼로 협주곡 1번 C장조',
      titleOriginal: 'Cello Concerto No. 1 in C major',
      composerId: 'haydn',
      composerKo: '하이든',
      composerOriginal: 'Joseph Haydn',
      period: '고전',
      instrumentation: '첼로',
      durationSeconds: 1500,
      catalogNumber: 'Hob. VIIb:1',
      aliases: ['하이든 첼로 협주곡 1번', 'Cello Concerto in C'],
      moodTags: ['밝은', '명료한', '경쾌한'],
      contextTags: ['첼로', '공연 전', '처음 듣기'],
      prompt: '첼로가 낮은 악기인데도 얼마나 또렷하고 가볍게 말하는지 들어보세요.',
      relatedWorkIds: ['saint-saens-swan', 'bach-cello-suite-1-prelude'],
      concertIds: const [],
    ),
    _work(
      id: 'scarlatti-sonata-k141',
      titleKo: '건반 소나타 K.141',
      titleOriginal: 'Keyboard Sonata in D minor',
      composerId: 'scarlatti',
      composerKo: '스카를라티',
      composerOriginal: 'Domenico Scarlatti',
      period: '바로크',
      instrumentation: '피아노',
      durationSeconds: 210,
      catalogNumber: 'K. 141',
      aliases: ['스카를라티 K141', 'Sonata K141'],
      moodTags: ['빠른', '반복', '명료한'],
      contextTags: ['피아노', '연습', '집중'],
      prompt: '반복음이 손끝에서 타악기처럼 튀는 질감을 들어보세요.',
      relatedWorkIds: ['chopin-revolutionary', 'mozart-piano-sonata-k545'],
      concertIds: const [],
    ),
    _work(
      id: 'purcell-dido-lament',
      titleKo: '디도의 탄식',
      titleOriginal: 'Dido and Aeneas: When I am laid in earth',
      composerId: 'purcell',
      composerKo: '퍼셀',
      composerOriginal: 'Henry Purcell',
      period: '바로크',
      instrumentation: '성악',
      durationSeconds: 240,
      catalogNumber: '',
      aliases: ['When I am laid in earth', '디도와 에네아스 탄식'],
      moodTags: ['어두운', '애절한', '선율'],
      contextTags: ['성악', '밤', '공연 전'],
      prompt: '반복되는 낮은 선율 위에서 목소리가 무너지는 방식을 들어보세요.',
      relatedWorkIds: ['schubert-ave-maria', 'handel-hallelujah'],
      concertIds: const [],
    ),
    _work(
      id: 'faure-pavane',
      titleKo: '파반느',
      titleOriginal: 'Pavane',
      composerId: 'faure',
      composerKo: '포레',
      composerOriginal: 'Gabriel Faure',
      period: '근현대',
      instrumentation: '오케스트라',
      durationSeconds: 360,
      catalogNumber: 'Op. 50',
      aliases: ['포레 파반느', 'Faure Pavane'],
      moodTags: ['차분한', '우아한', '선율'],
      contextTags: ['밤', '오케스트라', '공연 전'],
      prompt: '선율이 춤처럼 걷지만 끝까지 들뜨지 않는 균형을 들어보세요.',
      relatedWorkIds: ['debussy-clair-de-lune', 'ravel-bolero'],
      concertIds: const [],
    ),
    _work(
      id: 'faure-requiem-pie-jesu',
      titleKo: '레퀴엠: 피에 예수',
      titleOriginal: 'Requiem: Pie Jesu',
      composerId: 'faure',
      composerKo: '포레',
      composerOriginal: 'Gabriel Faure',
      period: '근현대',
      instrumentation: '성악',
      durationSeconds: 210,
      catalogNumber: 'Op. 48',
      aliases: ['포레 피에 예수', 'Pie Jesu'],
      moodTags: ['기도', '차분한', '선율'],
      contextTags: ['성악', '밤', '공연 전'],
      prompt: '높은 목소리가 크게 울리기보다 공중에 조용히 머무는 느낌을 들어보세요.',
      relatedWorkIds: ['schubert-ave-maria', 'purcell-dido-lament'],
      concertIds: const [],
    ),
    _work(
      id: 'bizet-carmen-habanera',
      titleKo: '카르멘: 하바네라',
      titleOriginal: 'Carmen: Habanera',
      composerId: 'bizet',
      composerKo: '비제',
      composerOriginal: 'Georges Bizet',
      period: '낭만',
      instrumentation: '성악',
      durationSeconds: 260,
      catalogNumber: '',
      aliases: ['하바네라', '카르멘 하바네라'],
      moodTags: ['관능적인', '익숙한', '리듬'],
      contextTags: ['성악', '처음 듣기', '공연 전'],
      prompt: '같은 리듬이 반복될수록 목소리가 더 여유롭게 흔드는지 들어보세요.',
      relatedWorkIds: ['rossini-william-tell', 'verdi-la-donna-mobile'],
      concertIds: const [],
    ),
    _work(
      id: 'bizet-carmen-toreador',
      titleKo: '카르멘: 투우사의 노래',
      titleOriginal: 'Carmen: Toreador Song',
      composerId: 'bizet',
      composerKo: '비제',
      composerOriginal: 'Georges Bizet',
      period: '낭만',
      instrumentation: '성악',
      durationSeconds: 300,
      catalogNumber: '',
      aliases: ['투우사의 노래', 'Toreador Song'],
      moodTags: ['웅장한', '익숙한', '밝은'],
      contextTags: ['성악', '공연 전', '처음 듣기'],
      prompt: '합창이 받쳐줄 때 독창 선율이 얼마나 무대 앞으로 나오는지 들어보세요.',
      relatedWorkIds: ['verdi-la-donna-mobile', 'handel-hallelujah'],
      concertIds: const [],
    ),
    _work(
      id: 'puccini-nessun-dorma',
      titleKo: '투란도트: 공주는 잠 못 이루고',
      titleOriginal: 'Turandot: Nessun dorma',
      composerId: 'puccini',
      composerKo: '푸치니',
      composerOriginal: 'Giacomo Puccini',
      period: '근현대',
      instrumentation: '성악',
      durationSeconds: 210,
      catalogNumber: '',
      aliases: ['네순 도르마', 'Nessun dorma'],
      moodTags: ['웅장한', '희망적인', '선율'],
      contextTags: ['성악', '공연 전', '처음 듣기'],
      prompt: '마지막 고음으로 달려가기 전 선율이 얼마나 오래 숨을 모으는지 들어보세요.',
      relatedWorkIds: ['verdi-la-donna-mobile', 'schubert-ave-maria'],
      concertIds: const [],
    ),
    _work(
      id: 'verdi-la-donna-mobile',
      titleKo: '리골레토: 여자의 마음',
      titleOriginal: 'Rigoletto: La donna e mobile',
      composerId: 'verdi',
      composerKo: '베르디',
      composerOriginal: 'Giuseppe Verdi',
      period: '낭만',
      instrumentation: '성악',
      durationSeconds: 150,
      catalogNumber: '',
      aliases: ['라 돈나 에 모빌레', 'La donna e mobile'],
      moodTags: ['밝은', '익숙한', '경쾌한'],
      contextTags: ['성악', '처음 듣기', '공연 전'],
      prompt: '짧은 선율이 왜 한 번 들으면 바로 따라 부르게 되는지 들어보세요.',
      relatedWorkIds: ['bizet-carmen-habanera', 'puccini-nessun-dorma'],
      concertIds: const [],
    ),
    _work(
      id: 'rossini-william-tell',
      titleKo: '윌리엄 텔 서곡 피날레',
      titleOriginal: 'William Tell Overture: Finale',
      composerId: 'rossini',
      composerKo: '로시니',
      composerOriginal: 'Gioachino Rossini',
      period: '낭만',
      instrumentation: '오케스트라',
      durationSeconds: 210,
      catalogNumber: '',
      aliases: ['윌리엄텔 서곡', 'William Tell Finale'],
      moodTags: ['빠른', '익숙한', '활기찬'],
      contextTags: ['오케스트라', '처음 듣기', '산책'],
      prompt: '말발굽처럼 달리는 리듬이 쉬지 않고 앞으로 밀어붙이는지 들어보세요.',
      relatedWorkIds: ['brahms-hungarian-dance-5', 'rimsky-flight-bumblebee'],
      concertIds: const [],
    ),
    _work(
      id: 'strauss-blue-danube',
      titleKo: '아름답고 푸른 도나우',
      titleOriginal: 'The Blue Danube',
      composerId: 'strauss-ii',
      composerKo: '요한 슈트라우스 2세',
      composerOriginal: 'Johann Strauss II',
      period: '낭만',
      instrumentation: '오케스트라',
      durationSeconds: 600,
      catalogNumber: 'Op. 314',
      aliases: ['푸른 도나우', 'Blue Danube'],
      moodTags: ['우아한', '왈츠', '익숙한'],
      contextTags: ['오케스트라', '산책', '처음 듣기'],
      prompt: '왈츠 박자가 크게 흔들리기 전에 현악기가 물결처럼 여는 부분을 들어보세요.',
      relatedWorkIds: [
        'tchaikovsky-nutcracker-waltz',
        'mendelssohn-wedding-march',
      ],
      concertIds: const [],
    ),
    _work(
      id: 'strauss-radetzky-march',
      titleKo: '라데츠키 행진곡',
      titleOriginal: 'Radetzky March',
      composerId: 'strauss-ii',
      composerKo: '요한 슈트라우스 2세',
      composerOriginal: 'Johann Strauss II',
      period: '낭만',
      instrumentation: '오케스트라',
      durationSeconds: 180,
      catalogNumber: 'Op. 228',
      aliases: ['라데츠키 행진곡', 'Radetzky March'],
      moodTags: ['밝은', '행진', '익숙한'],
      contextTags: ['행사', '오케스트라', '처음 듣기'],
      prompt: '짧은 악센트가 박수를 부르는 방식으로 반복되는지 들어보세요.',
      relatedWorkIds: ['mendelssohn-wedding-march', 'rossini-william-tell'],
      concertIds: const [],
    ),
    _work(
      id: 'holst-jupiter',
      titleKo: '행성: 목성',
      titleOriginal: 'The Planets: Jupiter',
      composerId: 'holst',
      composerKo: '홀스트',
      composerOriginal: 'Gustav Holst',
      period: '근현대',
      instrumentation: '오케스트라',
      durationSeconds: 480,
      catalogNumber: 'Op. 32 No. 4',
      aliases: ['홀스트 목성', 'Jupiter'],
      moodTags: ['웅장한', '희망적인', '선율'],
      contextTags: ['오케스트라', '공연 전', '집중'],
      prompt: '리듬이 활짝 뛰다가 넓은 찬가 선율로 바뀌는 순간을 들어보세요.',
      relatedWorkIds: ['sibelius-finlandia', 'beethoven-symphony-9'],
      concertIds: const [],
    ),
    _work(
      id: 'holst-mars',
      titleKo: '행성: 화성',
      titleOriginal: 'The Planets: Mars',
      composerId: 'holst',
      composerKo: '홀스트',
      composerOriginal: 'Gustav Holst',
      period: '근현대',
      instrumentation: '오케스트라',
      durationSeconds: 420,
      catalogNumber: 'Op. 32 No. 1',
      aliases: ['홀스트 화성', 'Mars'],
      moodTags: ['긴장', '어두운', '리듬'],
      contextTags: ['오케스트라', '집중', '공연 전'],
      prompt: '불규칙하게 밀고 오는 리듬이 음악 전체를 군사적으로 만드는지 들어보세요.',
      relatedWorkIds: ['beethoven-symphony-5', 'grieg-in-the-hall'],
      concertIds: const [],
    ),
    _work(
      id: 'bach-goldberg-aria',
      titleKo: '골드베르크 변주곡: 아리아',
      titleOriginal: 'Goldberg Variations: Aria',
      composerId: 'bach',
      composerKo: '바흐',
      composerOriginal: 'Johann Sebastian Bach',
      period: '바로크',
      instrumentation: '피아노',
      durationSeconds: 240,
      catalogNumber: 'BWV 988',
      aliases: ['골드베르크 아리아', 'Goldberg Aria'],
      moodTags: ['차분한', '명료한', '반복'],
      contextTags: ['피아노', '밤', '처음 듣기'],
      prompt: '아주 단순해 보이는 베이스가 변주곡 전체의 씨앗처럼 놓이는지 들어보세요.',
      relatedWorkIds: ['scarlatti-sonata-k141', 'satie-gymnopedie-1'],
      concertIds: const [],
    ),
    _work(
      id: 'mozart-requiem-lacrimosa',
      titleKo: '레퀴엠: 라크리모사',
      titleOriginal: 'Requiem: Lacrimosa',
      composerId: 'mozart',
      composerKo: '모차르트',
      composerOriginal: 'Wolfgang Amadeus Mozart',
      period: '고전',
      instrumentation: '합창',
      durationSeconds: 210,
      catalogNumber: 'K. 626',
      aliases: ['모차르트 라크리모사', 'Lacrimosa'],
      moodTags: ['어두운', '장엄한', '합창'],
      contextTags: ['성악', '공연 전', '처음 듣기'],
      prompt: '짧게 끊기는 현악 반주 위로 합창이 울먹이듯 올라오는지 들어보세요.',
      relatedWorkIds: ['handel-hallelujah', 'faure-requiem-pie-jesu'],
      concertIds: const [],
    ),
    _work(
      id: 'beethoven-pathetique-ii',
      titleKo: '비창 소나타 2악장',
      titleOriginal: 'Piano Sonata No. 8: II. Adagio cantabile',
      composerId: 'beethoven',
      composerKo: '베토벤',
      composerOriginal: 'Ludwig van Beethoven',
      period: '고전',
      instrumentation: '피아노',
      durationSeconds: 330,
      catalogNumber: 'Op. 13',
      aliases: ['비창 2악장', 'Pathetique Sonata 2nd Movement'],
      moodTags: ['따뜻한', '선율', '차분한'],
      contextTags: ['피아노', '밤', '처음 듣기'],
      prompt: '왼손 반주가 흔들리지 않는 동안 오른손 선율이 노래하듯 길어지는지 들어보세요.',
      relatedWorkIds: ['beethoven-moonlight', 'chopin-nocturne-op9-2'],
      concertIds: const [],
    ),
    _work(
      id: 'chopin-raindrop-prelude',
      titleKo: '빗방울 전주곡',
      titleOriginal: 'Prelude in D-flat major',
      composerId: 'chopin',
      composerKo: '쇼팽',
      composerOriginal: 'Frederic Chopin',
      period: '낭만',
      instrumentation: '피아노',
      durationSeconds: 330,
      catalogNumber: 'Op. 28 No. 15',
      aliases: ['쇼팽 빗방울', 'Raindrop Prelude'],
      moodTags: ['밤', '반복', '서정적인'],
      contextTags: ['피아노', '밤', '집중'],
      prompt: '같은 음이 빗방울처럼 계속 남아 있는데 분위기만 바뀌는지 들어보세요.',
      relatedWorkIds: ['debussy-clair-de-lune', 'satie-gymnopedie-1'],
      concertIds: const [],
    ),
    _work(
      id: 'debussy-arabesque-1',
      titleKo: '아라베스크 1번',
      titleOriginal: 'Deux arabesques: No. 1',
      composerId: 'debussy',
      composerKo: '드뷔시',
      composerOriginal: 'Claude Debussy',
      period: '인상주의',
      instrumentation: '피아노',
      durationSeconds: 240,
      catalogNumber: 'L. 66 No. 1',
      aliases: ['드뷔시 아라베스크', 'Arabesque No. 1'],
      moodTags: ['맑은', '부드러운', '선율'],
      contextTags: ['피아노', '아침', '처음 듣기'],
      prompt: '물결처럼 흐르는 반주 위에 선율이 가볍게 떠 있는지 들어보세요.',
      relatedWorkIds: ['debussy-clair-de-lune', 'ravel-bolero'],
      concertIds: const [],
    ),
    _work(
      id: 'ravel-pavane',
      titleKo: '죽은 왕녀를 위한 파반느',
      titleOriginal: 'Pavane pour une infante defunte',
      composerId: 'ravel',
      composerKo: '라벨',
      composerOriginal: 'Maurice Ravel',
      period: '근현대',
      instrumentation: '피아노',
      durationSeconds: 360,
      catalogNumber: 'M. 19',
      aliases: ['라벨 파반느', 'Pavane pour une infante defunte'],
      moodTags: ['우아한', '차분한', '그리운'],
      contextTags: ['피아노', '밤', '공연 전'],
      prompt: '느리게 걷는 리듬이 슬픔보다 오래된 기억처럼 들리는지 들어보세요.',
      relatedWorkIds: ['faure-pavane', 'debussy-clair-de-lune'],
      concertIds: const [],
    ),
  ];

  static final concerts = <ClassicalConcert>[
    ClassicalConcert(
      id: 'concert-piano-evening',
      title: '피아노로 시작하는 클래식 나이트',
      venue: '예술의전당 IBK챔버홀',
      region: '서울',
      startsAt: DateTime(2026, 9, 18, 19, 30),
      performers: const ['김하늘 Piano'],
      programWorkIds: const [
        'beethoven-moonlight',
        'chopin-nocturne-op9-2',
        'debussy-clair-de-lune',
        'liszt-liebestraum-3',
      ],
      composerIds: const ['beethoven', 'chopin', 'debussy', 'liszt'],
      instrumentTags: const ['피아노'],
      ticketUrl: 'https://www.sac.or.kr/',
      programRawText: 'Beethoven Piano Sonata No. 14 Moonlight; Chopin Nocturne Op. 9 No. 2; Debussy Clair de lune; Liszt Liebestraum No. 3',
    ),
    ClassicalConcert(
      id: 'concert-symphony-starter',
      title: '처음 듣는 교향곡: 베토벤과 드보르자크',
      venue: '롯데콘서트홀',
      region: '서울',
      startsAt: DateTime(2026, 9, 25, 20),
      performers: const ['서울 페스티벌 오케스트라'],
      programWorkIds: const [
        'beethoven-symphony-5',
        'beethoven-symphony-9',
        'dvorak-new-world',
      ],
      composerIds: const ['beethoven', 'dvorak'],
      instrumentTags: const ['오케스트라'],
      ticketUrl: 'https://www.lotteconcerthall.com/',
      programRawText: 'Beethoven Symphony No. 5; Beethoven Symphony No. 9; Dvorak Symphony No. 9 From the New World',
    ),
    ClassicalConcert(
      id: 'concert-baroque-night',
      title: '바흐와 현의 밤',
      venue: '금호아트홀 연세',
      region: '서울',
      startsAt: DateTime(2026, 10, 3, 19, 30),
      performers: const ['앙상블 인 C'],
      programWorkIds: const [
        'bach-cello-suite-1-prelude',
        'bach-air',
        'saint-saens-swan',
      ],
      composerIds: const ['bach', 'saint-saens'],
      instrumentTags: const ['첼로', '현악합주'],
      ticketUrl: 'https://www.kumhoarthall.com/',
      programRawText: 'Bach Cello Suite No. 1 Prelude; Bach Orchestral Suite No. 3 Air; Saint-Saens The Swan',
    ),
    ClassicalConcert(
      id: 'concert-classic-starter',
      title: '처음 가는 클래식 콘서트',
      venue: '세종문화회관 체임버홀',
      region: '서울',
      startsAt: DateTime(2026, 10, 11, 17),
      performers: const ['클래식 스타터 앙상블'],
      programWorkIds: const [
        'mozart-eine-kleine',
        'vivaldi-spring',
        'pachelbel-canon',
        'mendelssohn-wedding-march',
      ],
      composerIds: const ['mozart', 'vivaldi', 'pachelbel', 'mendelssohn'],
      instrumentTags: const ['바이올린', '현악합주', '오케스트라'],
      ticketUrl: 'https://www.sejongpac.or.kr/',
      programRawText: 'Mozart Eine kleine Nachtmusik; Vivaldi Spring; Pachelbel Canon in D; Mendelssohn Wedding March',
    ),
    ClassicalConcert(
      id: 'concert-impression-night',
      title: '달빛과 볼레로: 프랑스 음악 산책',
      venue: '부산문화회관 중극장',
      region: '부산',
      startsAt: DateTime(2026, 10, 17, 19),
      performers: const ['부산 모던 클래식 플레이어스'],
      programWorkIds: const [
        'debussy-clair-de-lune',
        'ravel-bolero',
        'satie-gymnopedie-1',
      ],
      composerIds: const ['debussy', 'ravel', 'satie'],
      instrumentTags: const ['피아노', '오케스트라'],
      ticketUrl: 'https://www.bscc.or.kr/',
      programRawText:
          'Debussy Clair de lune; Ravel Bolero; Satie Gymnopedie No. 1',
    ),
    ClassicalConcert(
      id: 'concert-chorus-night',
      title: '합창으로 듣는 클래식',
      venue: '대전예술의전당 아트홀',
      region: '대전',
      startsAt: DateTime(2026, 10, 24, 19),
      performers: const ['대전시립합창단'],
      programWorkIds: const ['handel-hallelujah', 'schubert-ave-maria'],
      composerIds: const ['handel', 'schubert'],
      instrumentTags: const ['합창', '성악'],
      ticketUrl: 'https://www.daejeon.go.kr/djac/',
      programRawText: 'Handel Messiah Hallelujah; Schubert Ave Maria',
    ),
  ];

  static const promotions = <ConcertPromotion>[
    ConcertPromotion(
      id: 'promo-piano-evening',
      concertId: 'concert-piano-evening',
      advertiserName: '예술의전당',
      sponsorLabel: 'Sponsored 공연',
      targetWorkIds: [
        'beethoven-moonlight',
        'chopin-nocturne-op9-2',
        'debussy-clair-de-lune',
      ],
      targetComposerIds: ['beethoven', 'chopin', 'debussy'],
      targetInstruments: ['피아노'],
      targetRegions: ['서울', '경기'],
    ),
    ConcertPromotion(
      id: 'promo-symphony-starter',
      concertId: 'concert-symphony-starter',
      advertiserName: '롯데콘서트홀',
      sponsorLabel: '추천 공연',
      targetWorkIds: ['beethoven-symphony-5', 'dvorak-new-world'],
      targetComposerIds: ['beethoven', 'dvorak'],
      targetInstruments: ['오케스트라'],
      targetRegions: ['서울', '경기'],
    ),
    ConcertPromotion(
      id: 'promo-classic-starter',
      concertId: 'concert-classic-starter',
      advertiserName: '세종문화회관',
      sponsorLabel: '처음 가기 좋은 공연',
      targetWorkIds: ['mozart-eine-kleine', 'vivaldi-spring'],
      targetComposerIds: ['mozart', 'vivaldi'],
      targetInstruments: ['바이올린', '현악합주', '오케스트라'],
      targetRegions: ['서울'],
    ),
  ];

  static ClassicalWork? workById(String id) {
    for (final work in works) {
      if (work.id == id) {
        return work;
      }
    }
    return null;
  }

  static ClassicalConcert? concertById(String id) {
    for (final concert in concerts) {
      if (concert.id == id) {
        return concert;
      }
    }
    return null;
  }
}

ClassicalWork _work({
  required String id,
  required String titleKo,
  required String titleOriginal,
  required String composerId,
  required String composerKo,
  required String composerOriginal,
  required String period,
  required String instrumentation,
  required int durationSeconds,
  required String catalogNumber,
  required List<String> aliases,
  required List<String> moodTags,
  required List<String> contextTags,
  required String prompt,
  required List<String> relatedWorkIds,
  required List<String> concertIds,
}) {
  final searchQuery = _searchQueryForWork(
    titleKo: titleKo,
    titleOriginal: titleOriginal,
    composerKo: composerKo,
    composerOriginal: composerOriginal,
    catalogNumber: catalogNumber,
    aliases: aliases,
  );
  return ClassicalWork(
    id: id,
    titleKo: titleKo,
    titleOriginal: titleOriginal,
    composerId: composerId,
    composerNameKo: composerKo,
    composerNameOriginal: composerOriginal,
    period: period,
    instrumentation: instrumentation,
    durationSeconds: durationSeconds,
    catalogNumber: catalogNumber,
    movements: <ClassicalMovement>[
      ClassicalMovement(
        id: '$id-main',
        title: '주요 악장/구간',
        order: 1,
        durationSeconds: durationSeconds,
      ),
    ],
    moodTags: moodTags,
    contextTags: contextTags,
    difficultyForListening: contextTags.contains('처음 듣기') ? 1 : 2,
    aliases: aliases,
    listeningMoments: <ListeningMoment>[
      ListeningMoment(
        id: '$id-30s',
        label: '처음 붙잡을 30초',
        startSeconds: 0,
        endSeconds: 30,
        prompt: prompt,
        tags: <String>[instrumentation, ...moodTags.take(2)],
        recommendedRecordingId: '$id-youtube-recording',
        fallbackExternalLinkId: '$id-youtube',
      ),
      ListeningMoment(
        id: '$id-3m',
        label: '3분으로 익숙해지기',
        startSeconds: 0,
        endSeconds: durationSeconds < 180 ? durationSeconds : 180,
        prompt: '처음 들린 지점이 다시 돌아오는지 기다려 보세요.',
        tags: <String>[...contextTags.take(2), 'repeat'],
        recommendedRecordingId: '$id-youtube-recording',
        fallbackExternalLinkId: '$id-youtube',
      ),
    ],
    externalLinks: _externalLinks(id, searchQuery),
    recordings: <ClassicalRecording>[
      ClassicalRecording(
        id: '$id-youtube-recording',
        provider: 'YouTube',
        title: '$titleKo 듣기',
        performer: 'Curated public recording',
        url: _youtubeSearch(searchQuery),
        displayPriority: 1,
      ),
      ClassicalRecording(
        id: '$id-spotify-recording',
        provider: 'Spotify',
        title: '$titleKo on Spotify',
        performer: 'Search result',
        url: _spotifySearch(searchQuery),
        displayPriority: 2,
      ),
    ],
    relatedWorkIds: relatedWorkIds,
    scoreLinks: <ExternalLink>[
      ExternalLink(
        id: '$id-imslp',
        platformId: 'imslp',
        label: 'IMSLP 악보 검색',
        url:
            'https://imslp.org/index.php?search=${Uri.encodeComponent(searchQuery)}',
        linkType: 'score_search',
      ),
    ],
    concertIds: concertIds,
  );
}

List<ExternalLink> _externalLinks(String workId, String query) {
  return <ExternalLink>[
    ExternalLink(
      id: '$workId-youtube',
      platformId: 'youtube',
      label: 'YouTube',
      url: _youtubeSearch(query),
      linkType: 'listen_search',
    ),
    ExternalLink(
      id: '$workId-spotify',
      platformId: 'spotify',
      label: 'Spotify',
      url: _spotifySearch(query),
      linkType: 'listen_search',
    ),
    ExternalLink(
      id: '$workId-apple',
      platformId: 'apple-music',
      label: 'Apple Music',
      url: 'https://music.apple.com/search?term=${Uri.encodeComponent(query)}',
      linkType: 'listen_search',
    ),
    ExternalLink(
      id: '$workId-melon',
      platformId: 'melon',
      label: 'Melon 검색',
      url:
          'https://www.melon.com/search/total/index.htm?q=${Uri.encodeComponent(query)}',
      linkType: 'listen_search',
    ),
  ];
}

String _searchQueryForWork({
  required String titleKo,
  required String titleOriginal,
  required String composerKo,
  required String composerOriginal,
  required String catalogNumber,
  required List<String> aliases,
}) {
  final terms = <String>[
    composerOriginal,
    titleOriginal,
    if (catalogNumber.isNotEmpty) catalogNumber,
    composerKo,
    titleKo,
    ...aliases.take(2),
  ];
  return terms
      .map((term) => term.trim())
      .where((term) => term.isNotEmpty)
      .toSet()
      .join(' ');
}

String _youtubeSearch(String query) {
  return 'https://www.youtube.com/results?search_query=${Uri.encodeComponent(query)}';
}

String _spotifySearch(String query) {
  return 'https://open.spotify.com/search/${Uri.encodeComponent(query)}';
}
